package com.komdox.chipsTrial.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;



@AllArgsConstructor
@NoArgsConstructor
@Entity
@Data
public class Player{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;  // This field is the primary key and its value is generated by the database.
    private String name;
    private int purse = 1000;

}

